version: '3'

# This docker-compose is for developer convenience, not for running in production.

services:

  # For running the python consumers
  app:
    build:
      context: .
      args:
        DEVELOPMENT: 1
    depends_on:
      - kafka
      - elasticsearch
      - mock_kbase_services
      - re_api
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}:/app
      - ${PWD}/scratch:/scratch
    environment:
      - KBASE_ENDPOINT=http://mock_kbase_services:5000/
      - DEVELOPMENT=1
      - PYTHONUNBUFFERED=true
      - RE_URL=http://re_api:5000
      - WORKSPACE_TOKEN=valid_admin_token
      - RE_API_TOKEN=valid_admin_token
      - GLOBAL_CONFIG_URL=file:///app/spec/config.yaml

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    hostname: kafka
    ports:
      - "127.0.0.1:9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: -Xmx512m -Xms512m

  # Required for kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "127.0.0.1:2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper:12888:13888

  # Mock server for various kbase endpoints (workspace, auth, catalog)
  mock_kbase_services:
    image: mockservices/mock_json_service:1.3
    ports:
      - "127.0.0.1:5001:5000"
    volumes:
      - ${PWD}/tests/mock_kbase_services:/config

  elasticsearch:
    image: elasticsearch:7.5.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"

  # Relation Engine API
  re_api:
    image: kbase/relation_engine_api:develop
    depends_on:
      - arangodb
      - mock_kbase_services
    environment:
      - WORKERS=2
      - KBASE_AUTH_URL=http://mock_kbase_services:5000/auth
      - KBASE_WORKSPACE_URL=http://mock_kbase_services:5000/ws
      - PYTHONUNBUFFERED=true
      - DB_URL=http://arangodb:8529
      - DB_USER=root

  # Arangodb server in cluster mode. Required for re_api.
  arangodb:
    image: arangodb:3.5.3
    ports:
      - "127.0.0.1:8529:8529"
    command: sh -c "arangodb --starter.local"
