# Configuration for Annotated Metagenome Assembly object
ws_type_to_indexes:
  KBaseMetagenomes.AnnotatedMetagenomeAssembly: annotated_metagenome_assembly

ws_subobjects:
  - "annotated_metagenome_assembly_features_version_2"

latest_versions:
  annotated_metagenome_assembly: "annotated_metagenome_assembly_2"
  annotated_metagenome_assembly_version: "annotated_metagenome_assembly_version_2"
  annotated_metagenome_assembly_features_version: "annotated_metagenome_assembly_features_version_2"

aliases:
  annotated_metagenome_assembly:
    - annotated_metagenome_assembly_2
    - annotated_metagenome_assembly_1
  annotated_metagenome_assembly_version:
    - annotated_metagenome_assembly_version_2
    - annotated_metagenome_assembly_version_1
  annotated_metagenome_assembly_features_version:
    - annotated_metagenome_assembly_features_version_2
    - annotated_metagenome_assembly_features_version_1

mappings:
  "annotated_metagenome_assembly_1":
    global_mappings: [ws_auth, ws_object]
    properties:
      size: {type: integer}
      source_id: {type: keyword}
      source: {type: keyword, copy_to: agg_fields}
      gc_content: {type: float}
      warnings: {type: keyword}
      num_contigs: {type: integer}
      mean_contig_length: {type: float}
      external_source_origination_date: {type: keyword}
      original_source_file_name: {type: keyword}
      environment: {type: keyword}
      num_features: {type: integer}
      publication_authors: {type: keyword, copy_to: agg_fields}
      publication_titles: {type: keyword, copy_to: agg_fields}
      molecule_type: {type: keyword}
      assembly_ref: {type: keyword}
      notes: {type: text, copy_to: agg_fields}

  "annotated_metagenome_assembly_2":
    global_mappings: [ws_auth, ws_object]
    properties:
      size: {type: long}
      source_id: {type: keyword}
      source: {type: keyword, copy_to: agg_fields}
      gc_content: {type: float}
      warnings: {type: text}
      num_contigs: {type: integer}
      mean_contig_length: {type: float}
      external_source_origination_date: {type: keyword}
      original_source_file_name: {type: keyword}
      environment: {type: keyword}
      num_features: {type: integer}
      publication_authors: {type: keyword, copy_to: agg_fields}
      publication_titles: {type: keyword, copy_to: agg_fields}
      molecule_type: {type: keyword}
      assembly_ref: {type: keyword}
      notes: {type: text, copy_to: agg_fields}

  "annotated_metagenome_assembly_version_1":
    global_mappings: [ws_auth, ws_object]
    properties:
      size: {type: integer}
      source_id: {type: keyword}
      source: {type: keyword, copy_to: agg_fields}
      gc_content: {type: float}
      warnings: {type: keyword}
      num_contigs: {type: integer}
      mean_contig_length: {type: float}
      external_source_origination_date: {type: keyword}
      original_source_file_name: {type: keyword}
      environment: {type: keyword}
      num_features: {type: integer}
      publication_authors: {type: keyword, copy_to: agg_fields}
      publication_titles: {type: keyword, copy_to: agg_fields}
      molecule_type: {type: keyword}
      assembly_ref: {type: keyword}
      notes: {type: text, copy_to: agg_fields}

  "annotated_metagenome_assembly_version_2":
    global_mappings: [ws_auth, ws_object]
    properties:
      size: {type: long}
      source_id: {type: keyword}
      source: {type: keyword, copy_to: agg_fields}
      gc_content: {type: float}
      warnings: {type: text}
      num_contigs: {type: integer}
      mean_contig_length: {type: float}
      external_source_origination_date: {type: keyword}
      original_source_file_name: {type: keyword}
      environment: {type: keyword}
      num_features: {type: integer}
      publication_authors: {type: keyword, copy_to: agg_fields}
      publication_titles: {type: keyword, copy_to: agg_fields}
      molecule_type: {type: keyword}
      assembly_ref: {type: keyword}
      notes: {type: text, copy_to: agg_fields}

  "annotated_metagenome_assembly_features_version_1":
    global_mappings: [ws_subobject, ws_auth, ws_object]
    properties:
      id: {type: keyword}
      type: {type: keyword, copy_to: agg_fields}
      size: {type: integer}
      contig_ids: {type: keyword, copy_to: agg_fields}
      starts: {type: integer}
      strands: {type: keyword}
      stops: {type: integer}
      functions: {type: keyword, copy_to: agg_fields}
      functional_descriptions: {type: keyword, copy_to: agg_fields}
      warnings: {type: keyword}
      parent_gene: {type: keyword}
      inference_data: {type: keyword}
      dna_sequence: {type: text}
      gc_content: {type: float}
      annotated_metagenome_assembly_size: {type: integer}
      annotated_metagenome_assembly_num_features: {type: integer}
      annotated_metagenome_assembly_num_contigs: {type: integer}
      annotated_metagenome_assembly_gc_content: {type: float}

  "annotated_metagenome_assembly_features_version_2":
    global_mappings: [ws_subobject, ws_auth, ws_object]
    properties:
      id: {type: keyword}
      type: {type: keyword, copy_to: agg_fields}
      size: {type: long}
      contig_ids: {type: keyword, copy_to: agg_fields}
      starts: {type: integer}
      strands: {type: keyword}
      stops: {type: integer}
      functions: {type: text, copy_to: agg_fields}
      functional_descriptions: {type: text, copy_to: agg_fields}
      warnings: {type: text}
      parent_gene: {type: keyword}
      inference_data: {type: keyword}
      dna_sequence: {type: keyword}
      gc_content: {type: float}
      annotated_metagenome_assembly_size: {type: long}
      annotated_metagenome_assembly_num_features: {type: integer}
      annotated_metagenome_assembly_num_contigs: {type: integer}
      annotated_metagenome_assembly_gc_content: {type: float}